require 'thor'
require 'json'
require 'fog'

require_relative '../vcloud_session'
require_relative '../fog_interface'
require_relative 'entity'
require_relative 'collection'
require_relative 'catalog_item'
require_relative 'catalog'
require_relative 'network'
require_relative 'vapp'
require_relative 'vdc'
require_relative 'vm'
